/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package br.com.sw2you.realmeet.facade;


import br.com.sw2you.realmeet.domain.model.RoomDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
import java.util.concurrent.CompletableFuture;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-12-31T11:42:32.607755-03:00[America/Sao_Paulo]")


@Validated
@Api(value = "rooms", description = "the rooms API")
public interface RoomsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /rooms/{id} : Return a rooms by ID
     *
     * @param id ID of the room (required)
     * @return OK (status code 200)
     *         or Unexpected error (status code 200)
     */
    @ApiOperation(value = "Return a rooms by ID", nickname = "getRoom", notes = "", response = RoomDTO.class, tags={ "room", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = RoomDTO.class),
            @ApiResponse(code = 200, message = "Unexpected error", response = Error.class) })
    @RequestMapping(value = "/rooms/{id}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    default CompletableFuture<ResponseEntity<RoomDTO>> getRoom(@ApiParam(value = "ID of the room",required=true) @PathVariable("id") Long id) {
        return CompletableFuture.supplyAsync(()-> {
            getRequest().ifPresent(request -> {
                for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                    if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                        String exampleString = "{ \"name\" : \"name\", \"id\" : 0, \"seats\" : 6 }";
                        ApiUtil.setExampleResponse(request, "application/json", exampleString);
                        break;
                    }
                }
            });
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }, Runnable::run);

    }

}
